name: Metrics
on:
  # 每天 00:00 自动更新
  schedule: [{cron: "0 0 * * *"}]
  # 允许手动触发
  workflow_dispatch:
  # 每次 push 到 main 分支时触发（方便调试）
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # 刚才设置的 Token
          token: ${{ secrets.METRICS_TOKEN }}

          # 基础配置
          user: lighterEB
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          
          # 插件配置（对应你原来想要的效果）
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # 输出文件名为 github-metrics.svg
          filename: github-metrics.svg
